apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellokube-deployment
  labels:
    app: hellokube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellokube
  template:
    metadata:
      labels:
        app: hellokube
    spec:
      containers:
        - name: hellokube
          image: CONTAINER_IMAGE
          ports:
            - containerPort: 3003
